### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by aroralanuk**
Moved the app inside Docker. 
Run 'docker-compose up --build' to run the server locally.

### CODE REVIEW

**Comment by hexalellogram** [comment]
I'll have to fix up Travis (in `.travis.yml`) before we can merge this
I will tackle this over the weekend

**Comment by aroralanuk** [comment]
Ok. I tried opening it in Travis CI, but it doesn't let me sign in to view it. It says 'access denied'.

**Comment by hexalellogram** [comment]
> Ok. I tried opening it in Travis CI, but it doesn't let me sign in to view it. It says 'access denied'.

Yeah it's under my personal Travis account so if you can't edit it that would make sense. But yeah I'll take a look at it this weekend.

**Comment by hexalellogram** [comment]
@aroralanuk you might also need to merge in the changes that Shravan just made with the other branch that just got merged into `main`

**Comment by hexalellogram** [comment]
@aroralanuk I noticed that all the files for the application were moved into `./app`. Do we need to move the `Pipfile` and `Pipfile.lock` as well?

**Pull request closed without merging**
