### PR TITLE
Postgres

### PR DESCRIPTION
**Pull request by aroralanuk**
I switched db from sqlite3 to Postgres.

### CODE REVIEW

**Review by hexalellogram — CHANGES_REQUESTED** [review]
Linting is failing to due to lack of trailing whitespace (check Travis logs) so it should be a simple fix to pass the linting.

**Comment by hexalellogram** [comment]
@aroralanuk `settings.py` needs to have one empty line at the end (currently the last line is not whitespace)

**Comment by aroralanuk** [comment]
@hexalellogram can you delete db.sqlite3 from main branch to resolve the conflict merge

**Review by hexalellogram — APPROVED** [review]
Looks good to me!

**Comment by hexalellogram** [comment]
@aroralanuk we just need to resolve the db conflict (shouldn't be difficult since you just migrated to Postgres) and we should be good!

**Review by hexalellogram — APPROVED** [review]
Looks good and ready to merge as long as @shravan1k gives the go ahead!

**Review by shravan1k — APPROVED** [review]

**Pull request merged**
